"""initial_schema

Revision ID: f5879b1bd8bb
Revises: 
Create Date: 2026-05-29 05:50:41.915609+00:00
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = 'f5879b1bd8bb'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legal_documents',
    sa.Column('source_code', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('jurisdiction', sa.String(length=120), nullable=True),
    sa.Column('document_type', sa.String(length=80), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('collected_date', sa.Date(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legal_documents'))
    )
    op.create_index(op.f('ix_legal_documents_source_code'), 'legal_documents', ['source_code'], unique=False)
    op.create_table('rule_sets',
    sa.Column('version', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rule_sets')),
    sa.UniqueConstraint('version', name=op.f('uq_rule_sets_version'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('evidence_chunks',
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_id', sa.String(length=120), nullable=False),
    sa.Column('heading', sa.String(length=300), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('article_no', sa.String(length=80), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('embedding_model', sa.String(length=80), nullable=True),
    sa.Column('index_version', sa.String(length=80), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['legal_documents.id'], name=op.f('fk_evidence_chunks_document_id_legal_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_chunks')),
    sa.UniqueConstraint('chunk_id', name=op.f('uq_evidence_chunks_chunk_id'))
    )
    op.create_index(op.f('ix_evidence_chunks_document_id'), 'evidence_chunks', ['document_id'], unique=False)
    op.create_table('projects',
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('risk_level', sa.String(length=40), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('pnu', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_projects_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_index(op.f('ix_projects_pnu'), 'projects', ['pnu'], unique=False)
    op.create_table('rules',
    sa.Column('rule_set_id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('input_fields', sa.JSON(), nullable=False),
    sa.Column('condition_json', sa.JSON(), nullable=True),
    sa.Column('result_template', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rule_set_id'], ['rule_sets.id'], name=op.f('fk_rules_rule_set_id_rule_sets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rules'))
    )
    op.create_index(op.f('ix_rules_rule_id'), 'rules', ['rule_id'], unique=False)
    op.create_index(op.f('ix_rules_rule_set_id'), 'rules', ['rule_set_id'], unique=False)
    op.create_table('actions',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('action_type', sa.String(length=40), nullable=False),
    sa.Column('current_use', sa.String(length=120), nullable=True),
    sa.Column('desired_use', sa.String(length=120), nullable=True),
    sa.Column('site_area', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('building_area', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_floor_area', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('floor_count_above', sa.Integer(), nullable=True),
    sa.Column('floor_count_under', sa.Integer(), nullable=True),
    sa.Column('parking_before', sa.Integer(), nullable=True),
    sa.Column('parking_after', sa.Integer(), nullable=True),
    sa.Column('site_conditions', sa.JSON(), nullable=True),
    sa.Column('construction_method', sa.String(length=120), nullable=True),
    sa.Column('business_purpose', sa.String(length=300), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('normalized_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_actions_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_actions'))
    )
    op.create_index(op.f('ix_actions_project_id'), 'actions', ['project_id'], unique=False)
    op.create_table('parcels',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('pnu', sa.String(length=32), nullable=False),
    sa.Column('standard_address', sa.String(length=300), nullable=True),
    sa.Column('jibun_address', sa.String(length=300), nullable=True),
    sa.Column('legal_dong_code', sa.String(length=20), nullable=True),
    sa.Column('land_category', sa.String(length=40), nullable=True),
    sa.Column('site_area', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('use_district', sa.String(length=120), nullable=True),
    sa.Column('district_unit_plan', sa.Boolean(), nullable=False),
    sa.Column('geometry_geojson', sa.JSON(), nullable=True),
    sa.Column('data_base_date', sa.Date(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_parcels_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parcels'))
    )
    op.create_index(op.f('ix_parcels_pnu'), 'parcels', ['pnu'], unique=False)
    op.create_index(op.f('ix_parcels_project_id'), 'parcels', ['project_id'], unique=False)
    op.create_table('buildings',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('parcel_id', sa.String(length=36), nullable=True),
    sa.Column('registry_pk', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('main_use', sa.String(length=120), nullable=True),
    sa.Column('building_area', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_floor_area', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('floor_count_above', sa.Integer(), nullable=True),
    sa.Column('floor_count_under', sa.Integer(), nullable=True),
    sa.Column('approval_date', sa.Date(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], name=op.f('fk_buildings_parcel_id_parcels')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_buildings_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_buildings'))
    )
    op.create_index(op.f('ix_buildings_parcel_id'), 'buildings', ['parcel_id'], unique=False)
    op.create_index(op.f('ix_buildings_project_id'), 'buildings', ['project_id'], unique=False)
    op.create_index(op.f('ix_buildings_registry_pk'), 'buildings', ['registry_pk'], unique=False)
    op.create_table('diagnosis_runs',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('action_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('rule_set_version', sa.String(length=80), nullable=True),
    sa.Column('rag_index_version', sa.String(length=80), nullable=True),
    sa.Column('data_base_date', sa.String(length=20), nullable=True),
    sa.Column('law_base_date', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], name=op.f('fk_diagnosis_runs_action_id_actions')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_diagnosis_runs_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diagnosis_runs'))
    )
    op.create_index(op.f('ix_diagnosis_runs_action_id'), 'diagnosis_runs', ['action_id'], unique=False)
    op.create_index(op.f('ix_diagnosis_runs_project_id'), 'diagnosis_runs', ['project_id'], unique=False)
    op.create_table('regulation_overlays',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('parcel_id', sa.String(length=36), nullable=True),
    sa.Column('layer_code', sa.String(length=80), nullable=True),
    sa.Column('layer_name', sa.String(length=200), nullable=False),
    sa.Column('regulation_type', sa.String(length=80), nullable=True),
    sa.Column('jurisdiction', sa.String(length=120), nullable=True),
    sa.Column('overlap_area', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('overlap_ratio', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('source_name', sa.String(length=120), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('data_base_date', sa.Date(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcels.id'], name=op.f('fk_regulation_overlays_parcel_id_parcels')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_regulation_overlays_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regulation_overlays'))
    )
    op.create_index(op.f('ix_regulation_overlays_layer_code'), 'regulation_overlays', ['layer_code'], unique=False)
    op.create_index(op.f('ix_regulation_overlays_parcel_id'), 'regulation_overlays', ['parcel_id'], unique=False)
    op.create_index(op.f('ix_regulation_overlays_project_id'), 'regulation_overlays', ['project_id'], unique=False)
    op.create_table('diagnosis_results',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('overall', sa.String(length=80), nullable=False),
    sa.Column('main_permit_type', sa.String(length=120), nullable=True),
    sa.Column('risk_level', sa.String(length=40), nullable=True),
    sa.Column('missing_info_count', sa.Integer(), nullable=False),
    sa.Column('required_actions', sa.JSON(), nullable=False),
    sa.Column('summary_payload', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['diagnosis_runs.id'], name=op.f('fk_diagnosis_results_run_id_diagnosis_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diagnosis_results')),
    sa.UniqueConstraint('run_id', name=op.f('uq_diagnosis_results_run_id'))
    )
    op.create_table('evidence_traces',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_id', sa.String(length=36), nullable=True),
    sa.Column('procedure_name', sa.String(length=120), nullable=False),
    sa.Column('source_title', sa.String(length=300), nullable=False),
    sa.Column('source_chunk_id', sa.String(length=120), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['evidence_chunks.id'], name=op.f('fk_evidence_traces_chunk_id_evidence_chunks')),
    sa.ForeignKeyConstraint(['run_id'], ['diagnosis_runs.id'], name=op.f('fk_evidence_traces_run_id_diagnosis_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_traces'))
    )
    op.create_index(op.f('ix_evidence_traces_chunk_id'), 'evidence_traces', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_evidence_traces_run_id'), 'evidence_traces', ['run_id'], unique=False)
    op.create_table('procedure_results',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('target', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('risk', sa.String(length=40), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['diagnosis_runs.id'], name=op.f('fk_procedure_results_run_id_diagnosis_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_procedure_results'))
    )
    op.create_index(op.f('ix_procedure_results_run_id'), 'procedure_results', ['run_id'], unique=False)
    op.create_table('reports',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('diagnosis_run_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('report_type', sa.String(length=80), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('content_json', sa.JSON(), nullable=True),
    sa.Column('disclaimer', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_run_id'], ['diagnosis_runs.id'], name=op.f('fk_reports_diagnosis_run_id_diagnosis_runs')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_reports_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_index(op.f('ix_reports_diagnosis_run_id'), 'reports', ['diagnosis_run_id'], unique=False)
    op.create_index(op.f('ix_reports_project_id'), 'reports', ['project_id'], unique=False)
    op.create_table('rule_execution_traces',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=120), nullable=False),
    sa.Column('rule_name', sa.String(length=200), nullable=False),
    sa.Column('input_fields', sa.JSON(), nullable=False),
    sa.Column('result', sa.String(length=120), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['diagnosis_runs.id'], name=op.f('fk_rule_execution_traces_run_id_diagnosis_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rule_execution_traces'))
    )
    op.create_index(op.f('ix_rule_execution_traces_run_id'), 'rule_execution_traces', ['run_id'], unique=False)
    op.create_table('required_documents',
    sa.Column('procedure_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedure_results.id'], name=op.f('fk_required_documents_procedure_id_procedure_results')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_required_documents'))
    )
    op.create_index(op.f('ix_required_documents_procedure_id'), 'required_documents', ['procedure_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_required_documents_procedure_id'), table_name='required_documents')
    op.drop_table('required_documents')
    op.drop_index(op.f('ix_rule_execution_traces_run_id'), table_name='rule_execution_traces')
    op.drop_table('rule_execution_traces')
    op.drop_index(op.f('ix_reports_project_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_diagnosis_run_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_procedure_results_run_id'), table_name='procedure_results')
    op.drop_table('procedure_results')
    op.drop_index(op.f('ix_evidence_traces_run_id'), table_name='evidence_traces')
    op.drop_index(op.f('ix_evidence_traces_chunk_id'), table_name='evidence_traces')
    op.drop_table('evidence_traces')
    op.drop_table('diagnosis_results')
    op.drop_index(op.f('ix_regulation_overlays_project_id'), table_name='regulation_overlays')
    op.drop_index(op.f('ix_regulation_overlays_parcel_id'), table_name='regulation_overlays')
    op.drop_index(op.f('ix_regulation_overlays_layer_code'), table_name='regulation_overlays')
    op.drop_table('regulation_overlays')
    op.drop_index(op.f('ix_diagnosis_runs_project_id'), table_name='diagnosis_runs')
    op.drop_index(op.f('ix_diagnosis_runs_action_id'), table_name='diagnosis_runs')
    op.drop_table('diagnosis_runs')
    op.drop_index(op.f('ix_buildings_registry_pk'), table_name='buildings')
    op.drop_index(op.f('ix_buildings_project_id'), table_name='buildings')
    op.drop_index(op.f('ix_buildings_parcel_id'), table_name='buildings')
    op.drop_table('buildings')
    op.drop_index(op.f('ix_parcels_project_id'), table_name='parcels')
    op.drop_index(op.f('ix_parcels_pnu'), table_name='parcels')
    op.drop_table('parcels')
    op.drop_index(op.f('ix_actions_project_id'), table_name='actions')
    op.drop_table('actions')
    op.drop_index(op.f('ix_rules_rule_set_id'), table_name='rules')
    op.drop_index(op.f('ix_rules_rule_id'), table_name='rules')
    op.drop_table('rules')
    op.drop_index(op.f('ix_projects_pnu'), table_name='projects')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_evidence_chunks_document_id'), table_name='evidence_chunks')
    op.drop_table('evidence_chunks')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('rule_sets')
    op.drop_index(op.f('ix_legal_documents_source_code'), table_name='legal_documents')
    op.drop_table('legal_documents')
    # ### end Alembic commands ###
